import React from 'react';

const One = () => {
    return (
        <div>
            <div className='story-header'>
                <h1>The Father</h1>
                <a className='link' href='https://mrskanenta.weebly.com/uploads/5/8/3/8/58387409/_the_father_text.pdf'>Read the story here</a>
            </div>
            <div className='story-body'>
                <h3>Let's analyze</h3>
                <p>In the story “The Father” by Raymond Carver a family gathers around a baby dressed in white with blue ribbons and blankets, admiring its features and debating who the baby resembles. Phyllis believes the baby loves their dad, and the grandmother comments on the baby's chubby hands. The mother calls the baby cute and healthy. The sisters examine the baby's eyes, lips, and nose, suggesting different family members but can't agree. Phyllis finally says the baby looks like their dad, and Carol agrees. When asked who their dad looks like, they all look at the kitchen where he sits. Phyllis says he looks like no one and starts to cry. Grandma hushes her, and they all look at the father, who sits pale and expressionless. This story fits into my research by showing how families seek connections in new members. The narrative resembles how a family is searching for similar traits in the others, reflecting the desire to understand that the baby's identity truly has not been shaped yet. This illustrates how our identity is being shaped by family and the way other people see us. The story effectively develops the theme of identity by showing a usual situation in a family with a newborn, where the family members try to figure out who the baby resembles. This scene highlights the family’s desire to see familiar traits in the baby, which speaks to their need for connection and belonging. One example of this theme is when the family members gather around the baby and admire its features. The grandmother exclaims, “Look at its little arm! So fat. And these little fingers! Just like its mother’s” (pg 1). This moment shows the family's effort to identify familiar traits in the baby, reinforcing their connection to the new family member. </p>
                <p>Another example is when the sisters try to determine whose nose the baby has, with Alice asserting, "It looks like somebody’s nose" (pg 2). Their discussion illustrates the importance they place on physical resemblance as a means of establishing identity within the family. A particularly poignant moment occurs when Phyllis asks who the baby looks like, and Carol states that it looks like Daddy (pg 2). However, when Phyllis then questions who their dad looks like, it becomes clear that he is seen as not resembling anyone. Phyllis’s realization that “Dad is not like anyone else” leads her to cry, highlighting a deeper sense of identity crisis within the family (pg 2). This moment underscores how the search for identity can also reveal feelings of isolation and disconnection, particularly when a family member is perceived as not fitting in. The story uses the family's attempts to find resemblances in the baby to explore themes of identity and belonging. Through their discussions and emotional reactions, the narrative shows how identity is closely connected to familial bonds, physical traits, and the desire for connection. The story effectively develops the theme of identity through the family's attempts to find resemblances in the newborn baby. Their discussions and emotional reactions highlight the importance of physical traits and familial bonds in establishing a sense of belonging. The poignant moment when Phyllis realizes that their dad doesn't look like anyone else underscores how the search for identity can reveal deeper feelings of isolation. Overall, the narrative illustrates how identity is intertwined with family connections and the desire for recognition and inclusion.</p>
            </div>
        </div>
    );
};

export default One;
